#! /bin/sh
binaries() {
	SPATH=$(IFS=:; for dir in $PATH; do echo "$dir"; done)
	find $SPATH -maxdepth 1 \( -type f -o -type l \) -perm +111 -printf "%f\n" 2> /dev/null
}

exec $(binaries | sort | uniq | launcher dmenu)
