#!/bin/sh

DIR=$(pwd)
DOC=$DIR/$1
                                                                               
/usr/bin/soffice -invisible "macro:///Standard.Module1.ConvertWordToPDF($DOC)"
                                                                               
