#!/bin/bash
BEGIN=$(date +%s.%N | cut -c 1-14)
while [ True ]
do
	NOW=$(date +%s.%N | cut -c 1-14)
	DIF=$(echo $NOW - $BEGIN | bc)
	SEC=$(echo $DIF%60 | bc)
	MIN=$(echo "($DIF-$SEC)/60" | bc)
	if [ "$1" == "-h" ]
	then
		echo "help
	-m gives time in minutes and seconds
	-s gives time in seconds only"
	exit 1
	elif [ "$1" == "-m" ]
	then
		CMD="echo -ne $MIN:$SEC\r"
	elif [ "$1" == "-s" ]
	then
		CMD="echo -ne $DIF\r"
	elif [ -z $1 ]
	then
		CMD="echo -ne $DIF\r"
	else
		echo "try stopwatch -h"
		exit 1
	fi
	$CMD
done
